# Generated by Django 4.2.25 on 2025-12-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={},
        ),
        migrations.RemoveField(
            model_name='workout',
            name='notes',
        ),
        migrations.AddField(
            model_name='workout',
            name='calories_burned',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='workout',
            name='intensity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workout',
            name='type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength'), ('flexibility', 'Flexibility'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
