# Generated by Django 4.2.25 on 2025-12-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workout_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='intensity',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='workout',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workout',
            name='type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength'), ('flexibility', 'Flexibility'), ('hiit', 'HIIT'), ('mobility', 'Mobility'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
